name: cat_pics
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.0.0
  json_annotation: ^4.6.0

  http: ^0.13.0
  provider: ^6.0.0

  breakpoints_mq: ^2.0.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
